name: hello_langchain
description: Dart langchain sample.
publish_to: none
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  langchain: ^0.8.0+1
  langchain_openai: ^0.8.0+1
  langchain_ollama: ^0.4.0+1
  fetch_api: 2.3.1
  freezed_annotation: ^3.1.0